# nginx-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crater-website
  namespace: crater
  labels:
    app: crater-website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crater-website
  template:
    metadata:
      labels:
        app: crater-website
    spec:
      containers:
        - name: crater-website-container
          image: harbor.act.buaa.edu.cn/crater/website:v0.1.2
          ports:
            - containerPort: 80

---
# nginx-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: crater-website-svc
  namespace: crater
spec:
  selector:
    app: crater-website
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8888
  type: ClusterIP
